Flb/close 228 ontology stadand magic methods
emmo-repo/EMMO-python pull request #246
Opened 2021-09-29 20:58 UTC by francescalb

# Description:

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

2021-11-01 08:52 UTC, CasperWA requested changes
Looking great. I have only some minor code optimizations and a more significant question concerning the `_sorted_entities()` method.

2021-11-01 08:52 UTC, CasperWA commented on ontopy/ontology.py
> +    def _sorted_entities(self):
When is this method used? I.e., what's the purpose of adding it in this PR?

2021-11-01 08:52 UTC, CasperWA commented on ontopy/ontology.py
> +        return sorted(e.iri for e in self.get_entities(
```suggestion
        return sorted(_.iri for _ in self.get_entities(
```
A trick in Python is to use an underscore (`_`) for an irrelevant variable. Here the `e` variable is, first of all, a bad name for a variable (it's difficult to understand what is meant by "e"), but other than that, it's not used for anything other than being the iterable variable. Mainly for the latter reason, you can use `_` instead, as it's not a necessary variable for further use.

2021-11-01 08:52 UTC, CasperWA commented on ontopy/ontology.py
> +                return i
```suggestion
            return i
```

2021-11-01 08:52 UTC, CasperWA commented on ontopy/ontology.py
> +                    return "_:"  # blank nodes are given random neg. storid
```suggestion
                return "_:"  # blank nodes are given random neg. storid
```

2021-11-01 08:52 UTC, CasperWA commented on tests/test_load_emmo.py
> +    EMMO_inf = get_emmo(None)
```suggestion
    EMMO_inferred_again = get_emmo(None)
```

2021-11-01 08:52 UTC, CasperWA commented on tests/test_load_emmo.py
> +    assert EMMO_inferred == EMMO_inf
```suggestion
    assert EMMO_inferred == EMMO_inferred_again
```

2021-11-01 08:52 UTC, CasperWA commented on tests/test_load_emmo.py
> +    assert EMMO_inferred != EMMO_inf
```suggestion
    assert EMMO_inferred != EMMO_inferred_again
```

2021-11-01 08:52 UTC, CasperWA commented on tests/test_load_emmo.py
> +    assert EMMO_inferred2 != EMMO_inf
```suggestion
    assert EMMO_inferred2 != EMMO_inferred_again
```

2021-11-01 08:52 UTC, CasperWA commented on tests/test_load_emmo.py
>      assert EMMO
```suggestion
    assert EMMO_inferred_again
    assert EMMO
```

2021-11-01 13:06 UTC, CasperWA requested changes

2021-11-01 13:06 UTC, CasperWA commented on ontopy/ontology.py
> +            yield s, p, o
```suggestion
        for subject, predicate, obj in self.world.get_triples():
            yield _unabbreviate(subject), _unabbreviate(predicate), _unabbreviate(obj)
```

2021-11-01 13:13 UTC, francescalb commented
Why?  I guess changing s to subject, p to predicate and o to obj can be done, but spo is quite standard when looking at triples I think. 

Then, doing the _unabreviate in the yield, do wish for that because it is faster or just because you think it is prettier? If it is faster I agree, but otherwise I am not a super fan of compacting code all the time, as it is more difficult to read for new people coming in I think.

2021-11-01 18:36 UTC, francescalb commented
OK, fixed.

2021-11-01 21:46 UTC, jesper-friis commented
Took a look at the conversation above. I am not sure I fully agree that using one-letter is always bad practice. In general I agree that descriptive variable names are good, but sensible use one-letter variables makes the the lines shorter and the code easier to read. If you just need an integer variable in a loop, I think that `i` or `n` are completely fine to use. The same is the case with `s`, `p` and `o` in triples. In contrary I am not much fan of `_` as a variable you actually use, but if you only want to loop over the objects in a set of triples I think it is fine to write `for _, _, o in triples: ...`.

2021-11-02 07:55 UTC, CasperWA commented
> Took a look at the conversation above. I am not sure I fully agree that using one-letter is always bad practice. In general I agree that descriptive variable names are good, but sensible use one-letter variables makes the the lines shorter and the code easier to read. If you just need an integer variable in a loop, I think that `i` or `n` are completely fine to use. The same is the case with `s`, `p` and `o` in triples. In contrary I am not much fan of `_` as a variable you actually use, but if you only want to loop over the objects in a set of triples I think it is fine to write `for _, _, o in triples: ...`.

The underscore is the accepted Pythonic way of defining un-used variables, specifically in the example you show above, but also in other cases, e.g., when a function returns a Triple type and all you need are one of those.

I think exactly because they are single-character variables they are _not_ easy to read, quite the contrary, it makes it impenetrable to understand, especially when the method or function names do not mention triples at all.
To align the variable naming a bit more, one can write out the "object" variable name, but append an underscore, as this is the way to avoid renaming built-ins according to PEP-8, i.e.: `for subject, predicate, object_ in get_me_some_triples(): ...`.

I agree that single-character variables can be used as iterating variables. This is common practice across several programming languages - but for ease of readability I'd like to strongly support more descriptive variable names throughout the code base.

2021-11-02 07:56 UTC, CasperWA approved these changes
This looks excellent to me now :) Thank you @francescalb !

2021-11-02 07:58 UTC, CasperWA commented
Everything said - we can always introduce our own standards for some variable naming, but I think it should be documented well then so there is a resource to go to if one is looking at this as a coder, but without an understanding of the content that's being worked with.

2021-11-02 12:02 UTC, CasperWA commented
This is all good for me. Let's discuss naming conventions perhaps in #245? As I'm doing a lot of different updates in the way of naming in that PR.

2021-11-02 12:04 UTC, merged

2021-11-02 12:18 UTC, CasperWA commented
Going through the code locally in my editor, I realize now you have overwritten the inherited `get_triples()` function. Was this intentional? If yes, perhaps it should reuse the same parameters and such? Either that, or the method should be renamed, e.g., to `get_unabbreviated_triples()` or something?

2021-11-02 12:23 UTC, CasperWA commented
The [latest commit from #245](https://github.com/emmo-repo/EMMO-python/pull/245/commits/5b67bf681df65982872ec8cf23af7a413e5a75da) includes my suggested change/fix for this.

2021-11-02 12:31 UTC, francescalb commented
You are right. That is not good at all. Your fix should be included.
Thanx!

2021-11-02 12:33 UTC, CasperWA commented
Great - I'll make an extra issue and PR for it and redact my other PR.