add logo to Readme and doc
emmo-repo/EMMO-python pull request #289
Opened 2021-11-09 12:05 UTC by m-abdollahi

ADD logo to README and DOC index.md

# Description:

## Type of change:

- [ ] Bug fix.
- [x] New feature.
- [x] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [x] Is the code easy to read and understand?
- [x] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [x] Has the documentation been updated as necessary?
- [x] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

- [x] ADD logo to README.MD file #287 
- [x] ADD logo to Doc/Index.MD file #287

2021-11-09 16:03 UTC, CasperWA requested changes
Thanks, but please make these links relative and avoid fencing it in a `p` tag - there is no need, use instead the `align` attribute of the `img` tag. Furthermore, it will probably look nicer if it's aligned right.

2021-11-10 13:56 UTC, CasperWA requested changes
Could you move this line up to be the first line in `README.md` as this doesn't look very good at the moment:
![image](https://user-images.githubusercontent.com/43357585/141125655-fea92d9d-e58d-4b2e-b616-037157b0d8ad.png)

Please also run:
```shell
pip install pre-commit invoke
SKIP=pylint pre-commit run --all-files
```
And commit the changed files afterwards.

2021-11-10 14:09 UTC, m-abdollahi commented
Okay, but I did not understand what you mean :)

2021-11-11 08:57 UTC, CasperWA requested changes

2021-11-11 08:57 UTC, CasperWA commented on README.md
> +<img src="docs/images/suspected_logo.png" width="40%" align="middle">
```suggestion
<img src="docs/images/suspected_logo.png" width="40%" align="right">

# EMMOntoPy

```

2021-11-11 08:57 UTC, CasperWA commented on README.md
> +<img src="docs/images/suspected_logo.png" width="40%" align="middle">
This is what I meant.

2021-11-11 13:05 UTC, CasperWA requested changes
No reason to add extra lines. After this this looks great :)

2021-11-11 13:05 UTC, CasperWA commented on README.md
> +
```suggestion
```

2021-11-11 13:05 UTC, CasperWA commented on README.md
> +
```suggestion
```

2021-11-11 13:05 UTC, CasperWA commented on docs/index.md
> +
```suggestion
```

2021-11-11 13:05 UTC, CasperWA commented on docs/index.md
> +
```suggestion
```

2021-11-12 10:03 UTC, CasperWA approved these changes
This is great - thank you @m-abdollahi ! :)

2021-11-12 10:03 UTC, merged